# How high does our dimension work?

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import corc.utils
# import corc
import matplotlib.pyplot as plt
import pickle
import corc.graph_metrics.uniforce
import corc.graph_metrics.neb
import numpy as np
import sklearn.metrics
import tqdm
import corc.our_datasets
import corc.create_datasets.complex_datasets

In [33]:
X,y = corc.create_datasets.complex_datasets.load_densired(dim=384, path="../../datasets/densired-hd.npz")
tmm = corc.graph_metrics.neb.NEB(X, y, dataset_name="densired-hd", tmm_regularization=0.001, n_init=5, batch_size=30, optimization_iterations=100)
tmm.fit(X)
y_pred = tmm.predict_with_target(X, target_number_classes=6)
ari = sklearn.metrics.adjusted_rand_score(y, y_pred)
ari

Mixture model fit took 144.39 seconds.
[[  368 30345]
 [  518  2694]
 [  775  1761]
 [  677  2690]
 [  490  4479]
 [  307 26777]
 [  296  1825]
 [  343  3505]
 [  799  1626]
 [  736  2739]
 [  321  4597]
 [  276  4339]
 [  273  2937]
 [  300  2964]
 [  258  2568]
 [  289  2099]
 [  646  2030]
 [  272  3372]
 [  318  4173]
 [  258  3374]
 [  426 26224]
 [  223  2587]
 [  281  2293]
 [  302  3674]
 [  248  1921]]
After filtering 25 components, we are left with 25 components


t-NEB: 100%|██████████| 9/9 [00:31<00:00,  3.45s/it]


0.1767013914369397

In [ ]:
y_pred = tmm.predict_with_target(X, target_number_classes=6)
ari = sklearn.metrics.adjusted_rand_score(y, y_pred)
ari

In [ ]:
X,y = corc.create_datasets.complex_datasets.load_densired(dim=128, path="../../datasets/densired-hd-soft.npz")
tmm = corc.graph_metrics.neb.NEB(X, y, dataset_name="densired-hd", tmm_regularization=0.01, n_init=5, batch_size=20, optimization_iterations=100)
tmm.fit(X)
y_pred = tmm.predict_with_target(X, target_number_classes=6)
ari = sklearn.metrics.adjusted_rand_score(y, y_pred)
ari

Mixture model fit took 29.59 seconds.
[[   3772       6]
 [     10  435955]
 [    891      36]
 [      1       1]
 [      1       1]
 [      1       1]
 [      6 1190437]
 [      1       1]
 [      5 1160246]
 [      1       1]
 [     25  183836]
 [      1       1]
 [      1       1]
 [     24  208165]
 [      1       1]
 [    853      10]
 [      1       1]
 [   1516       9]
 [      1       1]
 [    821      42]
 [   1457      13]
 [      1       1]
 [      1       1]
 [    607      16]
 [      1       1]]
After filtering 25 components, we are left with 7 components
[[3855    6]
 [ 891   36]
 [ 853   10]
 [1516    9]
 [ 821   42]
 [1457   13]
 [ 607   16]]


t-NEB: 100%|██████████| 3/3 [00:05<00:00,  1.84s/it]


0.2829589139300902

In [3]:
X,y = corc.create_datasets.complex_datasets.load_densired(dim=384, path="../../datasets/densired-hd-soft.npz")
tmm = corc.graph_metrics.neb.NEB(X, y, dataset_name="densired-hd", tmm_regularization=0.001, n_init=5, batch_size=20, optimization_iterations=100, min_cluster_size=100, max_elongation=1e7)
tmm.fit(X)
y_pred = tmm.predict_with_target(X, target_number_classes=6)
ari = sklearn.metrics.adjusted_rand_score(y, y_pred)

ari

Mixture model fit took 351.59 seconds.
[[   6159 9588454]
 [      4 4358795]
 [   1117      92]
 [      1       1]
 [      4 8994030]
 [      1       1]
 [      1       1]
 [     26  625282]
 [      1       1]
 [      1       1]
 [   1064      25]
 [      1       1]
 [      1       1]
 [      1       1]
 [      1       1]
 [    360     204]
 [      1       1]
 [    729      47]
 [      1       1]
 [      1       1]
 [    521     247]
 [      1       1]
 [      1       1]
 [      1       1]
 [      1       1]]
After filtering 25 components, we are left with 6 components
[[   6209 9588454]
 [   1117      92]
 [   1064      25]
 [    360     204]
 [    729      47]
 [    521     247]]


t-NEB: 100%|██████████| 2/2 [00:06<00:00,  3.03s/it]


0.12204212958572204

In [4]:
X,y = corc.create_datasets.complex_datasets.load_densired(dim=512, path="../../datasets/densired-hd-soft.npz")
tmm = corc.graph_metrics.neb.NEB(X, y, dataset_name="densired-hd", tmm_regularization=0.001, n_init=5, batch_size=20, optimization_iterations=100, min_cluster_size=100, max_elongation=1e7)
tmm.fit(X)
y_pred = tmm.predict_with_target(X, target_number_classes=6)
ari = sklearn.metrics.adjusted_rand_score(y, y_pred)

ari

Mixture model fit took 212.24 seconds.
[[7523  268]
 [ 530  438]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]
 [ 885   24]
 [   1    1]
 [   1    1]
 [   1    1]
 [ 776  117]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]
 [ 266  306]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]
 [   1    1]]
After filtering 25 components, we are left with 5 components
[[7543  268]
 [ 530  438]
 [ 885   24]
 [ 776  117]
 [ 266  306]]


t-NEB: 100%|██████████| 1/1 [00:02<00:00,  2.58s/it]

6 clusters is not achievable.
Working with 5 clusters instead.


0.028158029714245147

In [41]:
X,y = corc.create_datasets.complex_datasets.load_densired(dim=192, path="../../datasets/densired-hd-soft.npz")
tmm = corc.graph_metrics.neb.NEB(X, y, dataset_name="densired-hd", tmm_regularization=0.001, n_init=5, batch_size=150, optimization_iterations=100, max_elongation=1e7, min_cluster_size=100)
tmm.fit(X)
y_pred = tmm.predict_with_target(X, target_number_classes=6)
ari = sklearn.metrics.adjusted_rand_score(y, y_pred)
ari

Mixture model fit took 106.34 seconds.
[[   4524  207974]
 [      1       1]
 [     34  196849]
 [   1709      77]
 [      1       1]
 [      1       1]
 [      1       1]
 [      1       1]
 [      1       1]
 [      1       1]
 [   1511      52]
 [      1       1]
 [   1714      37]
 [      1       1]
 [      1       1]
 [      1       1]
 [      1       1]
 [      1       1]
 [    484      51]
 [      1       1]
 [      1       1]
 [      6 2302897]
 [      1       1]
 [      1       1]
 [      1       1]]
After filtering 25 components, we are left with 5 components
[[  4582 207974]
 [  1709     77]
 [  1511     52]
 [  1714     37]
 [   484     51]]


t-NEB: 100%|██████████| 1/1 [00:04<00:00,  4.70s/it]


6 clusters is not achievable.
Working with 5 clusters instead.


0.23467638182482503